
A = 10000; 
X = 250;
B = 20000;

% defining the simulation time
Tinit = 0; % initial time
Tfin = 25;  % final time

% Solve 
[t,y] = ode23s(@PT,[0 25],[A X B]);

% with y(:,2) we are saying to use the second column of the matrix y 
plot(t,y(:,2));
title('Solution ');
xlabel('Time');
ylabel('Solution of X');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%This file is automatically generated by Greatspn
%You can report bugs  by sending an e-mail to beccuti@di.unito.it
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function dydt =PT(t,y)

%Transition rates
k2 = 0.0001 / ( factorial(3) ) ;
k1 = 3e-07 / ( factorial(2) ) ;
k4 = 3.5;
k3 = 0.001;
%End Transition rates

%Place mapping
A = y(1);
X = y(2);
B = y(3);
%Place mapping

%ODE system
dA =  + k2 * 1 * X^3 + k1 * -1 * A^1 * X^2;
dX =  + k2 * -1 * X^3 + k1 * 1 * A^1 * X^2 + k4 * 1 + k3 * 1 * B^1;
dB =  + k4 * 1 + k3 * -1 * B^1;
dydt = [ dA; dX; dB];
%ODE system

end
